query Input {
  cart {
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            fabric_roll: metafield(namespace: "custom", key: "fabric_roll_variant_id") {
              value
            }
            surcharge_round: metafield(namespace: "custom", key: "surcharge_round_variant_id") {
              value
            }
            surcharge_oval: metafield(namespace: "custom", key: "surcharge_oval_variant_id") {
              value
            }
            surcharge_width: metafield(namespace: "custom", key: "surcharge_width_variant_id") {
              value
            }
            surcharge_rectangular: metafield(namespace: "custom", key: "surcharge_rectangular_variant_id") {
              value
            }
          }
        }
      }
      properties {
        key
        value
      }
    }
  }
}
