query Input {
  cart {
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          sku
          product {
            title
            metervare: metafield(namespace: "custom", key: "metervare") {
              value
            }
          }
        }
      }
      _length: attribute(key: "_length") {
        value
      }
      _width: attribute(key: "_width") {
        value
      }
      _metervare_variant_id: attribute(key: "_metervare_variant_id") {
        value
      }
      _price_per_cm: attribute(key: "_price_per_cm") {
        value
      }
      _shape_surcharge: attribute(key: "_shape_surcharge") {
        value
      }
      _image: attribute(key: "_image") {
        value
      }
      _shape_variant_id: attribute(key: "_shape_variant_id") {
        value
      }
      _metervare_title: attribute(key: "_metervare_title") {
        value
      }
    }
  }
}
