# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb5d48ed3b1144363e5b5c89b36caf59"
name = "bythemeter"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "textil-voksdug-bundler"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
